### ISSUE TITLE
Commit always tries to commit to master

### ISSUE THREAD

**Issue by playpianolikewoah** [thisconnect/nodegit-kit#12]
On this line of your `commit.js` https://github.com/thisconnect/nodegit-kit/blob/master/lib/commit.js#L27
You reference `Repository#getBranchCommit`. You have `master` hard coded in there and I am not sure why.

**Comment by thisconnect** [comment]
Mainly because checkout and branch #2 is not implemented yet, nodegit.commit currently does `git commit -am"message"`. I belive `Repository#getHeadCommit` would be correct and let you use a specific branch. Agree?

For NodeGit.diff I already have an internal api to get a commit and should support branch https://github.com/thisconnect/nodegit-kit/blob/master/lib/get.js

**Comment by thisconnect** [comment]
0.7.2 should work for you

**Comment by playpianolikewoah** [comment]
Thanks @thisconnect. I'll check it out.

**Comment by thisconnect** [comment]
please reopen if the problem still exists
